services:
  bot:
    ports:
      - '3000:80'
    volumes:
      - '.:/usr/src'
      - /usr/src/node_modules
      - "C:/Users/ilyas/JSON-keys/telegrambot-cafe-paycheks-1fc298f92623.json:/usr/src/keys/sa.json:ro"
    env_file:
      - .env.bot.dev
    command: npm run dev
    environment:
     - SHEETS_CREDENTIALS_PATH=/usr/src/keys/sa.json
     - SHEETS_SPREADSHEET_ID=1YHETrUvvgIcA_Bu2WICLqlnuYAGgyFCw08ox47kLM7M
